# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34d7d53980ce38e215f5dfbddd330b71063f27ec6204422b599c9cecede1b3bd7abe44aa90f7666dbbdd3d5557df846b6eac7de91ef0ed3de4c95de113401aac

test:
  secret_key_base: 69eb1775576be4786c56ed1db8113122ec3c6ce516fc6d1b6fd3584233d7c5044208a3c531095796edb9879a5c2303c4d13ad1ff4af6346ac78f0d675f7b1385

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
